apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailserver-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emailserver
  template:
    metadata:
      labels:
        app: emailserver
    spec:
      containers:
      - name: emailserver-container
        image: localhost:5000/emailserver:VERSION
        ports:
        - containerPort: 80
        - containerPort: 1000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: MAILGUN_DOMAIN
          value: sandbox2b7a4006f5924a22a387e93517f8c752.mailgun.org
        - name: MAILGUN_API_KEY
          value: 37a8d77da2038811ee8c9f4d6d077039-e5e67e3e-873eee73
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
